--@deprecated
-- local a = game:GetService("ReplicatedStorage").Game.GunShop.GunShopUI;
-- local b = decompile(a);
-- local c = string.split(b, "\n");

-- table.foreach(c, function(i,v)
--     if (string.find(v, 'doesPlayerOwn') and not string.find(v,'v27')) then
--         local d = c[i + 1];
--         local e = string.split(d, '"');
--         print(e[2])
--     end
-- end)